metadata.format.version = "1.1"

[versions]

runpaperversion = "1.20.4"
foliabundle = "1.20.2-R0.1-SNAPSHOT"

[libraries]
# This is the version we compile for, but we may use older/deprecated methods for backwards compatibility
paper = "com.destroystokyo.paper:paper-api:1.12.2-R0.1-SNAPSHOT"
folia = "dev.folia:folia-api:1.20.2-R0.1-SNAPSHOT"
# ConfigurationMaster for enhanced config management
configmaster = "com.github.thatsmusic99:ConfigurationMaster-API:v2.0.0-rc.1"
# Command Framework
commandframework = "cloud.commandframework:cloud-paper:1.8.4"
commandframework-annotations = "cloud.commandframework:cloud-annotations:1.8.4"
# ProtocolLib to patch packet based exploits
protocollib = "com.comphenix.protocol:ProtocolLib:5.1.0"
# NBT API for cross version nbt tag handling
nbtapi = "de.tr7zw:item-nbt-api:2.12.2"
# Useful Paper related tools
paperlib = "io.papermc:paperlib:1.0.8"
# Bukkit bStats
bstats = "org.bstats:bstats-bukkit:3.0.2"
# FastMath
fastmath = "org.apache.commons:commons-math3:3.6.1"
# Rule based number format used in first join messages to format to ordinal based on locale
icu4j = "com.ibm.icu:icu4j:74.2"
# Fast caching
caffeine = "com.github.ben-manes.caffeine:caffeine:3.1.8"
# XSeries for cross-version support
xseries = "com.github.cryptomorin:XSeries:9.8.0"
adventure-platform = "net.kyori:adventure-platform-bukkit:4.3.1"
adventure-text-minimessage = "net.kyori:adventure-text-minimessage:4.14.0"

[plugins]

runpaper = { id = "xyz.jpenilla.run-paper", version = "2.2.2" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
userdev = { id = "io.papermc.paperweight.userdev", version = "1.5.11" }

[bundles]
